name: Test

on: [push, pull_request]

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      min_version: 2.5

  test:
    needs: ruby-versions
    name: build (${{ matrix.ruby }} / ${{ matrix.os }})
    strategy:
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        exclude:
          - { os: windows-latest, ruby: 'truffleruby' }
          - { os: windows-latest, ruby: 'truffleruby-head' }
          - { os: windows-latest, ruby: 'jruby-head' }
          - { os: windows-latest, ruby: 'jruby' }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # 'bundle install' and cache
      - name: Run test
        run: bundle exec rake
        env:
          JRUBY_OPTS: -X+O
